#!/bin/bash

declare -a buci=('(‿ˠ‿)' '(_!_)' '(__!__)' '(_x_)' '(‿ꜟ‿)' '(   ㅅ   )' '🍑')

num_buci=${#buci[@]}

rand () {
	shuf -n 1 -i 1-$1
}

print_buci () {
	# Set foreground color to rand(1, 6)
	tput setaf $(rand 6)

	# Print buci
	echo ${buci[$(($(rand $num_buci) - 1))]}
	
	# Reset color
	tput sgr0
}

print_buci
