#!/bin/bash

declare -a buci=('(‿ˠ‿)' '(_!_)' '(__!__)' '(_x_)' '(‿ꜟ‿)' '(  ㅅ  )' '🍑' '(  Y  )')

num_buci=${#buci[@]}

rand () {
	shuf -n 1 -i 1-$1
}

shell () {
	tput setaf $(rand 6)
	tput bold
	read -e -p "${buci[$(($(rand $num_buci) - 1))]}@BUCI-SYSTEM:$(pwd)# " input
	if [ -n "${input// }" ]; then
		history -s "$input"
	fi
	tput sgr0
	$input
}

trap ' ' SIGINT

while true
do shell
done