#!/bin/sh
buci="(‿ˠ‿):(_!_):(__!__):(_x_):(‿ꜟ‿):(   ㅅ   ):🍑"
total_buci=$(( $(echo $buci | tr -cd : | wc -c) + 1 ))

random_buci () {
    return $(shuf -e $(seq -s ' ' 1 $total_buci) | tr '\n' ' ' | cut -d' ' -f1)
}

print_buci () {
  echo
  random_buci
  echo $buci | cut -d':' -f$?
}

print_buci
